<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="C:\Dev\EdwardsFoundation\JoanCEdwards.DAO\JoanCEdwards.DAO.Tests\bin\Release\JoanCEdwards.DAO.Tests.dll" total="5" errors="0" failures="1" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2010-07-17" time="13:01:52">
  <environment nunit-version="2.5.5.10112" clr-version="2.0.50727.4927" os-version="Microsoft Windows NT 6.1.7600.0" platform="Win32NT" cwd="C:\Dev\EdwardsFoundation\JoanCEdwards.DAO\JoanCEdwards.DAO.Tests\bin\Release" machine-name="PATRICKSULL8171" user="Administrator" user-domain="PATRICKSULL8171" />
  <culture-info current-culture="en-US" current-uiculture="en-US" />
  <test-suite type="Assembly" name="C:\Dev\EdwardsFoundation\JoanCEdwards.DAO\JoanCEdwards.DAO.Tests\bin\Release\JoanCEdwards.DAO.Tests.dll" executed="True" result="Failure" success="False" time="2.502" asserts="0">
    <results>
      <test-suite type="Namespace" name="JoanCEdwards" executed="True" result="Failure" success="False" time="2.499" asserts="0">
        <results>
          <test-suite type="Namespace" name="DAO" executed="True" result="Failure" success="False" time="2.499" asserts="0">
            <results>
              <test-suite type="Namespace" name="Tests" executed="True" result="Failure" success="False" time="2.498" asserts="0">
                <results>
                  <test-suite type="TestFixture" name="UserProfileTests" executed="True" result="Failure" success="False" time="2.497" asserts="0">
                    <results>
                      <test-case name="JoanCEdwards.DAO.Tests.UserProfileTests.UserProfile_WhenAddingMultiple_IsTheRightSize" executed="True" result="Success" success="True" time="2.261" asserts="1" />
                      <test-case name="JoanCEdwards.DAO.Tests.UserProfileTests.UserProfile_WhenAddTwoProfilesWithSameEmailAddress_ErrorOccurs" executed="True" result="Failure" success="False" time="0.025" asserts="0">
                        <failure>
                          <message><![CDATA[System.InvalidOperationException was expected]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="JoanCEdwards.DAO.Tests.UserProfileTests.UserProfile_WhenDeleted_IsNotRemovedFromTheDatabase" executed="True" result="Success" success="True" time="0.152" asserts="1" />
                      <test-case name="JoanCEdwards.DAO.Tests.UserProfileTests.UserProfile_WhenRetrieved_IsWhatWasStored" executed="True" result="Success" success="True" time="0.014" asserts="6" />
                      <test-case name="JoanCEdwards.DAO.Tests.UserProfileTests.UserProfile_WhenStored_ReturnsId" executed="True" result="Success" success="True" time="0.038" asserts="1" />
                    </results>
                  </test-suite>
                </results>
              </test-suite>
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>