<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="C:\Dev\EdwardsFoundation\JoanCEdwards.DAO\JoanCEdwards.DAO.Tests\bin\Release\JoanCEdwards.DAO.Tests.dll" total="5" errors="1" failures="0" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2010-07-17" time="13:22:18">
  <environment nunit-version="2.5.5.10112" clr-version="2.0.50727.4927" os-version="Microsoft Windows NT 6.1.7600.0" platform="Win32NT" cwd="C:\Dev\EdwardsFoundation\JoanCEdwards.DAO\JoanCEdwards.DAO.Tests\bin\Release" machine-name="PATRICKSULL8171" user="Administrator" user-domain="PATRICKSULL8171" />
  <culture-info current-culture="en-US" current-uiculture="en-US" />
  <test-suite type="Assembly" name="C:\Dev\EdwardsFoundation\JoanCEdwards.DAO\JoanCEdwards.DAO.Tests\bin\Release\JoanCEdwards.DAO.Tests.dll" executed="True" result="Failure" success="False" time="1.747" asserts="0">
    <results>
      <test-suite type="Namespace" name="JoanCEdwards" executed="True" result="Failure" success="False" time="1.742" asserts="0">
        <results>
          <test-suite type="Namespace" name="DAO" executed="True" result="Failure" success="False" time="1.742" asserts="0">
            <results>
              <test-suite type="Namespace" name="Tests" executed="True" result="Failure" success="False" time="1.742" asserts="0">
                <results>
                  <test-suite type="TestFixture" name="UserProfileTests" executed="True" result="Failure" success="False" time="1.741" asserts="0">
                    <results>
                      <test-case name="JoanCEdwards.DAO.Tests.UserProfileTests.UserProfile_WhenAddingMultiple_IsTheRightSize" executed="True" result="Error" success="False" time="1.369" asserts="0">
                        <failure>
                          <message><![CDATA[System.Data.SqlClient.SqlException : Cannot insert duplicate key row in object 'dbo.UserProfile' with unique index 'IX_UserProfile'.
The statement has been terminated.]]></message>
                          <stack-trace><![CDATA[at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection)
at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection)
at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning()
at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
at System.Data.SqlClient.SqlDataReader.ConsumeMetaData()
at System.Data.SqlClient.SqlDataReader.get_MetaData()
at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async)
at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, DbAsyncResult result)
at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
at System.Data.Common.DbCommand.ExecuteReader()
at System.Data.Linq.SqlClient.SqlProvider.Execute(Expression query, QueryInfo queryInfo, IObjectReaderFactory factory, Object[] parentArgs, Object[] userArgs, ICompiledSubQuery[] subQueries, Object lastResult)
at System.Data.Linq.SqlClient.SqlProvider.ExecuteAll(Expression query, QueryInfo[] queryInfos, IObjectReaderFactory factory, Object[] userArguments, ICompiledSubQuery[] subQueries)
at System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query)
at System.Data.Linq.ChangeDirector.StandardChangeDirector.DynamicInsert(TrackedObject item)
at System.Data.Linq.ChangeDirector.StandardChangeDirector.Insert(TrackedObject item)
at System.Data.Linq.ChangeProcessor.SubmitChanges(ConflictMode failureMode)
at System.Data.Linq.DataContext.SubmitChanges(ConflictMode failureMode)
at JoanCEdwards.DAO.Tests.UserProfileTests.UserProfile_WhenAddingMultiple_IsTheRightSize() in C:\Dev\EdwardsFoundation\JoanCEdwards.DAO\JoanCEdwards.DAO.Tests\UserProfileTests.cs:line 59
]]></stack-trace>
                        </failure>
                      </test-case>
                      <test-case name="JoanCEdwards.DAO.Tests.UserProfileTests.UserProfile_WhenAddTwoProfilesWithSameEmailAddress_ErrorOccurs" executed="True" result="Success" success="True" time="0.116" asserts="0" />
                      <test-case name="JoanCEdwards.DAO.Tests.UserProfileTests.UserProfile_WhenDeleted_IsNotRemovedFromTheDatabase" executed="True" result="Success" success="True" time="0.126" asserts="1" />
                      <test-case name="JoanCEdwards.DAO.Tests.UserProfileTests.UserProfile_WhenRetrieved_IsWhatWasStored" executed="True" result="Success" success="True" time="0.014" asserts="6" />
                      <test-case name="JoanCEdwards.DAO.Tests.UserProfileTests.UserProfile_WhenStored_ReturnsId" executed="True" result="Success" success="True" time="0.109" asserts="1" />
                    </results>
                  </test-suite>
                </results>
              </test-suite>
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>